config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :creatures

  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags


end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
FlickRaw.api_key=ENV["API_KEY"]
FlickRaw.shared_secret=ENV["API_SECRET"]


class CreaturesController < ApplicationController



  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def create
    @creature = Creature.create(creature_params)

    # render :json => params

    tags = params[:creature][:tag_ids]
    tags.each do |t|
      @creature.tags << Tag.find(t) unless t.blank?
    end
    redirect_to @creature
  end

  def show
    @creature = Creature.find(params[:id])
    @tag = @creature.tags

    list = flickr.photos.search :text => @creature.name, :sort => "relevance"
    photos = list.map do |i|
       "https:/farm3.static.flickr.com/#{i["server"]}/" "#{i["id"]}_" "#{i["secret"]}_n.jpg"
    end
    @photo = photos.sample



  end

  def edit
    @creature = Creature.find(params[:id])
    @tags = Tag.all

  end

  def update
    @creature = Creature.find(params[:id])
    @creature.update(creature_params)

    @creature.tags.clear

    tags = params[:creature][:tag_ids]
    tags.each do |t|
      @creature.tags << Tag.find(t) unless t.blank?
    end


    redirect_to @creature


  end

  def destroy
    @creature = Creature.destroy(params[:id])
    redirect_to @creature
  end

  private

  def creature_params
    params.require(:creature).permit(:name,:desc)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # @creatures = Creature.all
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

def index
  @tags = Tag.all
end


def new
  @tag = Tag.new()
end

def create
  @tag = Tag.create(tag_params)
  redirect_to tags_path #:tags

end

def edit
  @tag = Tag.find(params[:id])
end

def update
   @tag = Tag.update(params[:id], tag_params)
  redirect_to tags_path
end

def show
    @tag = Tag.find(params[:id])
    @creatures = @tag.creatures

  end

def destroy

   @tag = Tag.find(params[:id])


   if @tag.creatures.length == 1

    flash[:danger] = "Can't delete! There is #{ @tag.creatures.length } creature using this tag!"

   elsif @tag.creatures.length > 1

    flash[:danger] = "Can't delete! There are #{ @tag.creatures.length } creatures using this tag!"

   else

    @tag.destroy

  end



    redirect_to tags_path
end

private

def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creatures/edit.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
<h1>Edit creature</h1>
    <%= bootstrap_form_for @creature do |c| %>
  <%= c.text_field :name, :placeholder =>"Enter a Creature" %>
  <%= c.text_field :desc, :placeholder =>"Describe it!" %>
  <%= c.collection_check_boxes :tag_ids, @tags, :id, :name %>

  <%= c.primary :class => 'btn btn-success' %>
  <% end %>
  </div>
</div>

app/views/creatures/index.html.erb
<div class="row">
<div class="container col-md-4 col-md-offset-4">
<h1>Creatures of the Bog</h1>

<% @creatures.each do |c| %>

  <li><%= link_to c.name, c %></li>

<% end %>

<br>
<br>

<%= link_to "Add a new Creature", new_creature_path, :class=>"btn btn-success"%>

</div>
</div>

app/views/creatures/new.html.erb
<div class="row">
  <div class="container col-md-4 col-md-offset-4">
<h1 id="headerstyle">Create a Creature</h1>
  <%= bootstrap_form_for @creature do |c| %>
  <%= c.text_field :name, :placeholder =>"Name it!", :class => 'formstyle' %>
  <%= c.text_field :desc, :placeholder =>"Describe it!", :class => 'formstyle' %>
  <%= c.collection_check_boxes :tag_ids, @tags, :id, :name %>
  <%= c.primary :class => 'btn btn-success' %>
  <% end %>
  </div>
</div>

app/views/creatures/show.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">

<h1 class="heady"><%= @creature.name %></h1>


<p class="textty">Description:<br> <%= @creature.desc %> <br> Tags: <br>

 <!-- <%= @creature.tags.map{|t| t.name}.join(', ') %> -->

  <% @tag.each do |t| %>
      <li class="creatures"><%= link_to t.name, t %></li>
    <% end %>



</p>

<!--
  <%=  @creature.tags.each do |t|

  link_to t.name, tag_path(t)

 end %>
 -->

<img src=<%= @photo %>>

<br>
<%= link_to "Edit Creature", edit_creature_path, :class=>"btn btn-success" %>
<%= link_to "Remove Creature", @creature, :method => :delete, :class=>"btn btn-danger" %>
</div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="container col-md-4 col-md-offset-4">

<h1>Home page</h1>

<p>This site is dedicated to tracking all the amazing creatures in our local Bogs!</p>

<div id="carousel-id" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-id" data-slide-to="0" class=""></li>
        <li data-target="#carousel-id" data-slide-to="1" class=""></li>
        <li data-target="#carousel-id" data-slide-to="2" class="active"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item">
            <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzc3NyI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojN2E3YTdhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+Rmlyc3Qgc2xpZGU8L3RleHQ+PC9zdmc+">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Example headline.</h1>
                    <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzY2NiI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojNmE2YTZhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+U2Vjb25kIHNsaWRlPC90ZXh0Pjwvc3ZnPg==">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="item active">
            <img data-src="holder.js/900x500/auto/#555:#5a5a5a/text:Third slide" alt="Third slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzU1NSI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojNWE1YTVhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+VGhpcmQgc2xpZGU8L3RleHQ+PC9zdmc+">
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

</div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>


<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Bogs</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/creatures">Creatures</a></li>
      <li><a href="/creatures/new">Add Creature</a></li>
      <li><a href="/tags">Tags</a></li>
      <li><a href="/tags/new">Add Tag</a></li>
    </ul>
    <!-- <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
    <!-- <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li> -->
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
</div>
</div>
</head>
<body>
<div class="container divvy col-md-10 col-md-offset-1">
<%= yield %>
</div>

</body>
</html>

app/views/tags/edit.html.erb
<div class="row">
<div class="container col-md-4 col-md-offset-4">
<h1>Edit Tag</h1>


<%= bootstrap_form_for @tag do |t| %>
  <%= t.text_field :name, :placeholder =>"Name it!", :class => 'formstyle' %>

  <%= t.primary :class => 'btn btn-success' %>
  <% end %>




</div>
</div>

app/views/tags/index.html.erb
<div class="row">
<div class="container col-md-4 col-md-offset-4">
<h1>Tags of the Bog</h1>

 <%= render "layouts/flash" %>


<% @tags.each do |t| %>

  <li>
  <%=  link_to t.name, t %>
  <%= link_to "edit", edit_tag_path(t.id), :class=>"btn btn-success" %>
  <%= link_to "Delete", t, :method => :delete, :class=>"btn btn-danger" %>

</li>

<% end %>



</div>
</div>

app/views/tags/new.html.erb
<div class="row">
<div class="container col-md-4 col-md-offset-4">
<h1>Create a tag</h1>


<%= bootstrap_form_for @tag do |t| %>
  <%= t.text_field :name, :placeholder =>"Name it!", :class => 'formstyle' %>

  <%= t.primary :class => 'btn btn-success' %>
  <% end %>




</div>
</div>

app/views/tags/show.html.erb
<div class="row">
<div class="container col-md-4 col-md-offset-4">
<h1>Tag</h1>

<h1><%= @tag.name %></h1>


<% @creatures.each do |c| %>

  <li><%= link_to c.name, c %></li>

<% end %>




</div>
</div>